import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import localFont from "next/font/local";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { ToastContainer } from "react-toastify";
import ToastProvider from "@/provider/ToastProvider";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "700", "800"],
});

export const fontBangla = localFont({
  src: "../fonts/mayaboti-normal.ttf",
});

// export const metadata = {
//   title: {
//     default: "Hero Kidz",
//     template: "%s | Hero Kidz",
//   },
//   description: "Generated by create next app",
// };

export const metadata = {
  metadataBase: new URL("https://playwisekids.vercel.app/"),

  title: {
    default: "Kids Learning Toys - Educational Toys for Smart Learning",
    template: "%s | Kids Learning Toys",
  },

  description:
    "Discover educational toys, learning boards, puzzles, STEM kits, Montessori toys, and creative learning products designed to make learning fun and engaging for children.",

  keywords: [
    "Educational Toys",
    "Learning Toys",
    "Kids Learning Board",
    "Montessori Toys",
    "STEM Toys",
    "Math Learning Toys",
    "Puzzle Toys",
    "Children Education",
    "Kids Toy Shop Bangladesh",
    "Learning Through Play",
  ],

  authors: [
    {
      name: "Mehedi Hasan",
    },
  ],

  creator: "Mehedi Hasan",
  publisher: "Kids Learning Toys",

  robots: {
    index: true,
    follow: true,
  },

  openGraph: {
    title: "Kids Learning Toys - Educational Toys for Smart Learning",
    description:
      "Shop educational toys, learning boards, puzzles, and STEM kits that help children learn while having fun.",
    url: "https://playwisekids.vercel.app/",
    siteName: "Kids Learning Toys",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Kids Learning Toys",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "Kids Learning Toys",
    description:
      "Educational toys, puzzles, STEM kits, and learning boards for children.",
    images: ["/og-image.jpg"],
  },

  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/logo.png",
  },

  category: "E-Commerce",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased`}>
          <header className="py-2 md:w-11/12 mx-auto w-full">
            <Navbar />
          </header>

          <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-300px)]">
            {children}
            <ToastProvider/>
          </main>

          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </NextAuthProvider>
  );
}
